# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

timesTwoRcpp <- function(x_) {
    .Call('gammatest_timesTwoRcpp', PACKAGE = 'gammatest', x_)
}

gammalnRcpp <- function(x_) {
    .Call('gammatest_gammalnRcpp', PACKAGE = 'gammatest', x_)
}

gammaRcpp <- function(a_, x_) {
    .Call('gammatest_gammaRcpp', PACKAGE = 'gammatest', a_, x_)
}

gammaScaledRcpp <- function(x_, a_) {
    .Call('gammatest_gammaScaledRcpp', PACKAGE = 'gammatest', x_, a_)
}

erfRcpp <- function(x_) {
    .Call('gammatest_erfRcpp', PACKAGE = 'gammatest', x_)
}

normcdfRcpp <- function(x_, mu_, sigma_) {
    .Call('gammatest_normcdfRcpp', PACKAGE = 'gammatest', x_, mu_, sigma_)
}

betacfRcpp <- function(a_, b_, x_) {
    .Call('gammatest_betacfRcpp', PACKAGE = 'gammatest', a_, b_, x_)
}

betaiRcpp <- function(a_, b_, x_) {
    .Call('gammatest_betaiRcpp', PACKAGE = 'gammatest', a_, b_, x_)
}

tcdfRcpp <- function(t_, nu_) {
    .Call('gammatest_tcdfRcpp', PACKAGE = 'gammatest', t_, nu_)
}

