// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// timesTwoRcpp
Rcpp::NumericVector timesTwoRcpp(Rcpp::NumericVector x_);
RcppExport SEXP gammatest_timesTwoRcpp(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwoRcpp(x_));
    return rcpp_result_gen;
END_RCPP
}
// gammalnRcpp
Rcpp::NumericVector gammalnRcpp(Rcpp::NumericVector x_);
RcppExport SEXP gammatest_gammalnRcpp(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(gammalnRcpp(x_));
    return rcpp_result_gen;
END_RCPP
}
// gammaRcpp
Rcpp::NumericVector gammaRcpp(Rcpp::NumericVector a_, Rcpp::NumericVector x_);
RcppExport SEXP gammatest_gammaRcpp(SEXP a_SEXP, SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_(a_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(gammaRcpp(a_, x_));
    return rcpp_result_gen;
END_RCPP
}
// gammaScaledRcpp
Rcpp::NumericVector gammaScaledRcpp(Rcpp::NumericVector x_, Rcpp::NumericVector a_);
RcppExport SEXP gammatest_gammaScaledRcpp(SEXP x_SEXP, SEXP a_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_(a_SEXP);
    rcpp_result_gen = Rcpp::wrap(gammaScaledRcpp(x_, a_));
    return rcpp_result_gen;
END_RCPP
}
// erfRcpp
Rcpp::NumericVector erfRcpp(Rcpp::NumericVector x_);
RcppExport SEXP gammatest_erfRcpp(SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(erfRcpp(x_));
    return rcpp_result_gen;
END_RCPP
}
// normcdfRcpp
Rcpp::NumericVector normcdfRcpp(Rcpp::NumericVector x_, Rcpp::NumericVector mu_, Rcpp::NumericVector sigma_);
RcppExport SEXP gammatest_normcdfRcpp(SEXP x_SEXP, SEXP mu_SEXP, SEXP sigma_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu_(mu_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sigma_(sigma_SEXP);
    rcpp_result_gen = Rcpp::wrap(normcdfRcpp(x_, mu_, sigma_));
    return rcpp_result_gen;
END_RCPP
}
// betacfRcpp
Rcpp::NumericVector betacfRcpp(Rcpp::NumericVector a_, Rcpp::NumericVector b_, Rcpp::NumericVector x_);
RcppExport SEXP gammatest_betacfRcpp(SEXP a_SEXP, SEXP b_SEXP, SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_(a_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_(b_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(betacfRcpp(a_, b_, x_));
    return rcpp_result_gen;
END_RCPP
}
// betaiRcpp
Rcpp::NumericVector betaiRcpp(Rcpp::NumericVector a_, Rcpp::NumericVector b_, Rcpp::NumericVector x_);
RcppExport SEXP gammatest_betaiRcpp(SEXP a_SEXP, SEXP b_SEXP, SEXP x_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type a_(a_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type b_(b_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_(x_SEXP);
    rcpp_result_gen = Rcpp::wrap(betaiRcpp(a_, b_, x_));
    return rcpp_result_gen;
END_RCPP
}
// tcdfRcpp
Rcpp::NumericVector tcdfRcpp(Rcpp::NumericVector t_, Rcpp::NumericVector nu_);
RcppExport SEXP gammatest_tcdfRcpp(SEXP t_SEXP, SEXP nu_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type t_(t_SEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type nu_(nu_SEXP);
    rcpp_result_gen = Rcpp::wrap(tcdfRcpp(t_, nu_));
    return rcpp_result_gen;
END_RCPP
}
